language: java
jdk:
  - oraclejdk8
dist: trusty 
install: true
sudo: required
services:
  - docker
script: mvn --settings ./.travis/settings.xml -Dstyle.color=always -V clean install
cache:
  directories:
    - "$HOME/.m2"
